select = ["E", "F", "Q"]
ignore = ["E501", "E401", "E701"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = []
per-file-ignores = {}

# Same as Black.
line-length = 100

# Assume Python 3.8
target-version = "py38"

[flake8-quotes]
inline-quotes = "single"
