default:
  - _self_

cmd:
  - prep

prep:
  doctype: snt  # 'rvw' for single review, but 'snt' for segmented subreviews
  languag: ['', 'pes_Arab', 'zho_Hans', 'deu_Latn', 'arb_Arab', 'fra_Latn', 'spa_Latn']
  translator: nllb
  nllb: facebook/nllb-200-distilled-600M
  max_l: 1500
  device: ${oc.env:CUDA_VISIBLE_DEVICES, "cpu"} # Use CUDA if available, esle CPU
  batch: true